### ISSUE TITLE
Rating request from original authors

### ISSUE THREAD

**Issue by bimlas** [bimlas/vim-high#19]
@dodie, @blueyed, @lfv89, @nathanaelkane, @ntpeters, @Valloric, @whatyouhide:

I made a [universal plugin](https://github.com/bimlas/vim-high) based on [your works](https://github.com/bimlas/vim-high#plugins-that-inspired). I'm curious about your opinion: what should I improve to let it the de facto Vim highlighter plugin?

**Comment by blueyed** [comment]
@bimlas 
I have not looked too closely yet.
As with Neovim there is a better approach for dimming the window (https://github.com/neovim/neovim/pull/6597#issuecomment-299475512), which I plan to add to vim-diminactive also.
For your plugin the comment/snippet linked above might suffice already then?
