### ISSUE TITLE
Is it possible to customize inactive_window?

### ISSUE THREAD

**Issue by jesseleite** [bimlas/vim-high#21]
Firstly, love the plugin! ❤️

I've been reading the source code & tests, but it doesn't seem `inactive_window` highlighting is customizable.  Is it possible to define extra highlight groups to be dimmed?  For example, the following git gutter and user `CursorLineNR` highlighting aren't dimmed:

<img width="1412" alt="screen shot on 2018-05-19 at 19_23_50" src="https://user-images.githubusercontent.com/5187394/40274022-98fbd380-5b9a-11e8-870c-e2fc6abe87c4.png">

Also, is it possible that instead of dimming to the `Comment` highlight group, that you could create dim to something like `VimHighDimmed` so that we could customize the exact appearance of dimmed content?

What are your thoughts on all this?

**Comment by bimlas** [comment]
Thanks for your contribution; I'm glad you like the plugin.

Customization is a core functionality of the plugin: if you want to use `VimHighDimmed` highlight group in `inactive_window`, you can use the following codes in your _.vimrc_:

```viml
autocmd ColorScheme,VimEnter *
\ highlight! VimHighDimmed guibg=#fade00 guifg=#063642

let g:high_lighters = {'inactive_window': {'hlgroup': 'VimHighDimmed'}}
```

Vim-High operates on highlighting (see `:help matchadd`), while `CursorLineNR` and Git gutter signs are using different approaches which are out of the plugin's scope, thus it cannot modify them. I'm sorry, but I don't like to extend the plugin to support different "coloring" methods (like `:help sign`), because it would contract the Unix philosophy ("Write programs that do one thing and do it well.").

**Comment by jesseleite** [comment]
Hmm, thank you for reply.

I read the `:help sign` docs, etc. and am confused because both `CursorLineNR` and git gutter highlighting (via `GitGutterAdd`, `GitGutterChange`, etc.) can be seen in the `:highlight` list, and overridden with a simple:

```
highlight CursorLineNR ctermbg=green ctermfg=green
highlight GitGutterAdd ctermbg=green ctermfg=green
```

I'm missing how you mean they are coloured using different approaches?

**Comment by bimlas** [comment]
The plugin is basically `macthadd()` on steroids, it highlights the matching regex patterns, thus it cannot modify the highlighting itself, but apply those on the matched texts. Besides this, the plugin operates **inside the buffer**, but signs and line numbers are not parts of it.

**Comment by jesseleite** [comment]
Darn, fair enough.  I understand that it's out of ~buffer~ er, scope 😬 I mean, I understand gitgutter is 3rd party sure, but `CursorLineNR` is native vim highlighting, which is nothing fancy.  If I can customize with `highlight CursorLineNR ctermbg=green`, wouldn't it be cool to dim anything that's listed in `:highlight`?  If that were possible, then **_users_** could add any highlight groups they feel necessary to an `inactive_window` dimmable array.

```
let g:high_lighters = {
\ 'inactive_window': {'hlgroup': 'VimHighDimmed', 'dimmable': ['CursorLineNR', 'GitGutterAdd']},
\ }
```

Not sure on best implementation within `inactive_window` there, but the ability to pass an array of user-defined highlights that the user also wants dimmable.  Again, I understand the technical limitations, but I'm thinking from a user's standpoint.

Anyway, I appreciate the conversation!  I understand if you would rather not.  Just my $0.02!

**Comment by bimlas** [comment]
Though about it, but it's simply not in the plugin's scope: if I would implement it then somebody else could request to change the color of statusline for example. The plugin is about highlighting, not "coloring", sorry.
